// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// odds_ratios.cpp
writable::data_frame pairwise_fisher_exact(integers_matrix<> mat);
extern "C" SEXP _clover_pairwise_fisher_exact(SEXP mat) {
  BEGIN_CPP11
    return cpp11::as_sexp(pairwise_fisher_exact(cpp11::as_cpp<cpp11::decay_t<integers_matrix<>>>(mat)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_clover_pairwise_fisher_exact", (DL_FUNC) &_clover_pairwise_fisher_exact, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_clover(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
