# Generated by cpp11: do not edit by hand

charging_odds_ratios_counts_cpp <- function(n11, n10, n01, n00, min_reads, min_margin, max_p) {
  .Call(`_clover_charging_odds_ratios_counts_cpp`, n11, n10, n01, n00, min_reads, min_margin, max_p)
}

charging_odds_ratios_cpp <- function(ref_idx, pos_idx, modified, charged, n_refs, n_pos, min_reads, min_margin, max_p) {
  .Call(`_clover_charging_odds_ratios_cpp`, ref_idx, pos_idx, modified, charged, n_refs, n_pos, min_reads, min_margin, max_p)
}

pairwise_fisher_exact <- function(mat) {
  .Call(`_clover_pairwise_fisher_exact`, mat)
}
