globalVariables(c(
  "ref",
  "base",
  "mis",
  "ins",
  "del",
  "q_std",
  "error_rate",
  "strand",
  "ACGT",
  "BC_delta",
  "sprinzl_label",
  "global_index",
  "region",
  "residue",
  "trna_id",
  "base_num",
  "suffix",
  "suffix_order",
  "sort_key",
  "value",
  "label",
  "counts_charged",
  "counts_uncharged",
  "cpm_charged",
  "cpm_uncharged",
  "sample_id",
  "total_count",
  "pos1",
  "pos2",
  "odds_ratio",
  "log_odds_ratio",
  "p_value",
  "total_obs",
  "from",
  "to",
  "or_numerator",
  "or_denominator",
  "ror",
  "log_ror",
  "condition",
  "charge_status",
  # New pipeline bcerror column names (pre-rename)
  "Reference",
  "Position",
  "Spanning_Reads",
  "A_Freq",
  "T_Freq",
  "G_Freq",
  "C_Freq",
  "MismatchFreq",
  "InsertionFreq",
  "DeletionFreq",
  "BCErrorFreq",
  "MeanQual",
  # New derived names
  "a_freq",
  "t_freq",
  "g_freq",
  "c_freq",
  "cov",
  "mean_qual",
  # compute_odds_ratios
  "read_id",
  "ref_position",
  "chrom",
  "within_alignment",
  "call_code",
  "modified",
  # modomics
  "mod_full",
  "mod1",
  "subtype",
  "anticodon",
  "seq",
  # charging_count_matrix
  "col_name",
  "count",
  # compute_ror
  "mean_log_or",
  # .add_modification_ring
  "pos",
  # .map_to_sprinzl
  "from_idx",
  "to_idx",
  "from_label",
  "to_label",
  # compute_charging_diffs
  "charging_ratio",
  "mean_ratio",
  "se_ratio",
  "total",
  "diff",
  "se_diff",
  "ratio_numerator",
  "ratio_denominator",
  "se_numerator",
  "se_denominator",
  # plot_bcerror_profile
  "mean_error",
  # plot_mod_heatmap annotations
  ".label_display",
  ".text_color",
  # .add_region_shading
  ".xmin",
  ".xmax",
  ".seg_id",
  ".region_change",
  # plot_abundance_charging
  "quadrant",
  "log2FoldChange",
  # odds-ratios
  "isodecoder",
  "log_or_clean",
  "mean_or",
  "sd_log_or",
  "min_pval",
  "n_copies",
  "mean_log_or_num",
  "mean_log_or_den",
  "se_num",
  "se_den",
  "ror_se",
  "z_score",
  "p_adj",
  "ci_lower",
  "ci_upper",
  "significant",
  # rewiring
  "comparison",
  "euclidean_magnitude",
  "mean_abs_change",
  "max_abs_change",
  "n_nonzero",
  "PC1",
  "PC2",
  # plot-network
  "edge_type",
  "weight",
  "degree",
  "betweenness",
  "position"
))
