#' Read a counts TSV file.
#'
#' Read a per-tRNA counts file produced by the tRNA sequencing pipeline.
#'
#' @param path Path to a counts TSV file (may be gzipped).
#'
#' @return A tibble.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' read_counts("sample1.counts.tsv.gz")
#' }
read_counts <- function(path) {
  readr::read_tsv(path, show_col_types = FALSE)
}

#' Read base-calling error ("bcerror") TSV files.
#'
#' bcerror files are generated by the tRNA sequencing pipeline. Each file
#' contains per-position error rate statistics for a single sample.
#'
#' Columns returned:
#' - `ref`: reference tRNA name
#' - `pos`: position in reference (1-based)
#' - `cov`: coverage (spanning reads)
#' - `a_freq`, `t_freq`, `g_freq`, `c_freq`: nucleotide frequencies
#' - `mis`: mismatch frequency
#' - `ins`: insertion frequency
#' - `del`: deletion frequency
#' - `error_rate`: total base-calling error (mis + ins + del)
#' - `mean_qual`: mean base quality at position
#'
#' @param bcerr_path Path to bcerror file.
#'
#' @return A tibble.
#'
#' @export
#'
#' @examples
#' bcerr_path <- clover_example(
#'   "ecoli/summary/tables/wt-15-ctl-01/wt-15-ctl-01.bcerror.tsv.gz"
#' )
#' read_bcerror(bcerr_path)
read_bcerror <- function(bcerr_path) {
  raw_tbl <- readr::read_tsv(bcerr_path, show_col_types = FALSE)

  raw_tbl |>
    dplyr::rename(
      "ref" = "Reference",
      "pos" = "Position",
      "cov" = "Spanning_Reads",
      "a_freq" = "A_Freq",
      "t_freq" = "T_Freq",
      "g_freq" = "G_Freq",
      "c_freq" = "C_Freq",
      "mis" = "MismatchFreq",
      "ins" = "InsertionFreq",
      "del" = "DeletionFreq",
      "error_rate" = "BCErrorFreq",
      "mean_qual" = "MeanQual"
    ) |>
    dplyr::mutate(
      pos = as.integer(.data$pos)
    ) |>
    dplyr::select(
      "ref",
      "pos",
      "cov",
      "a_freq",
      "t_freq",
      "g_freq",
      "c_freq",
      "mis",
      "ins",
      "del",
      "error_rate",
      "mean_qual"
    )
}

#' Compute per-position delta between two conditions.
#'
#' Take a summarized bcerror tibble (with columns for reference, position,
#' condition, and a value such as mean error rate) and compute the
#' difference between two conditions at each position.
#'
#' @param data A summarized bcerror tibble with at least `ref`, `pos`,
#'   and columns named by `value_col` and `condition_col`.
#' @param delta A bare expression of the form `lhs - rhs`, where `lhs`
#'   and `rhs` are condition levels. The result is `lhs - rhs`.
#' @param value_col Column name (string) containing the values to
#'   pivot. Default `"mean_error"`.
#' @param condition_col Column name (string) containing condition
#'   labels. Default `"condition"`.
#'
#' @return A tibble with columns `ref`, `pos`, one column per condition
#'   level, and `delta` (the computed difference).
#'
#' @export
#'
#' @examples
#' df <- tidyr::expand_grid(
#'   ref = c("tRNA-Ala", "tRNA-Gly"),
#'   pos = 1:5,
#'   condition = c("wt", "mut")
#' )
#' df$mean_error <- runif(nrow(df), 0, 0.3)
#' compute_bcerror_delta(df, delta = wt - mut)
compute_bcerror_delta <- function(
  data,
  delta,
  value_col = "mean_error",
  condition_col = "condition"
) {
  expr <- rlang::enexpr(delta)

  if (!rlang::is_call(expr, "-") || length(expr) != 3L) {
    cli_abort(
      "{.arg delta} must be an expression of the form {.code lhs - rhs}."
    )
  }

  lhs <- as.character(expr[[2]])
  rhs <- as.character(expr[[3]])

  levels <- unique(data[[condition_col]])
  if (!lhs %in% levels) {
    cli_abort(
      "Level {.val {lhs}} not found in column {.field {condition_col}}."
    )
  }
  if (!rhs %in% levels) {
    cli_abort(
      "Level {.val {rhs}} not found in column {.field {condition_col}}."
    )
  }

  data |>
    dplyr::select(
      dplyr::all_of(c("ref", "pos", condition_col, value_col))
    ) |>
    tidyr::pivot_wider(
      names_from = dplyr::all_of(condition_col),
      values_from = dplyr::all_of(value_col)
    ) |>
    dplyr::mutate(
      delta = .data[[lhs]] - .data[[rhs]]
    )
}
